spring:
#  datasource:
#    name: demo
#    type: com.alibaba.druid.pool.DruidDataSource
#    #druid相关配置
#    druid:
#      #监控统计拦截的filters
#      filters: stat
#      driver-class-name: com.mysql.jdbc.Driver
#      #基本属性
#      url: jdbc:mysql://localhost:3306/spring_security?useUnicode=true&useSSL=false&characterEncoding=UTF-8&allowMultiQueries=true
#      username: root
#      password: root
#      #配置初始化大小/最小/最大
#      initial-size: 1
#      min-idle: 1
#      max-active: 20
#      #获取连接等待超时时间
#      max-wait: 60000
#      #间隔多久进行一次检测，检测需要关闭的空闲连接
#      time-between-eviction-runs-millis: 60000
#      #一个连接在池中最小生存的时间
#      min-evictable-idle-time-millis: 300000
#      validation-query: SELECT 'x'
#      test-while-idle: true
#      test-on-borrow: false
#      test-on-return: false
#      #打开PSCache，并指定每个连接上PSCache的大小。oracle设为true，mysql设为false。分库分表较多推荐设置为false
#      pool-prepared-statements: false
#      max-pool-prepared-statement-per-connection-size: 20
  # 热部署
#  devtools:
#    remote:
#      restart:
#        #热部署生效
#        enabled: true
#    restart:
#      #设置重启的目录
#      additional-paths: src/main/java
#      #classpath目录下的WEB-INF文件夹内容修改不重启
#      exclude: templates

#  mvc:
#    view:
#      prefix: classpath:/templates/
#      suffix: .jsp
#      returnPageInfo: check
  # 模板引擎
  thymeleaf:
    cache: false
    check-template-location: true
    servlet:
      content-type: text/html
    enabled: true
    encoding: UTF-8
    mode: HTML
    prefix: classpath:/templates/
    suffix: .html


## 该配置节点为独立的节点，有很多同学容易将这个配置放在spring的节点下，导致配置无法被识别
#mybatis:
#  mapper-locations: classpath:mapper/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
#  type-aliases-package: com.example.demo.model  # 注意：对应实体类的路径



